# Generated by Django 5.2.9 on 2025-12-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='language',
            field=models.CharField(choices=[('auto', 'Auto Detect'), ('english', 'English'), ('hindi', 'Hindi')], max_length=20),
        ),
    ]
