# Generated by Django 5.2.9 on 2025-12-27 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transcription_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('technical', 'Technical Support'), ('billing', 'Billing & Payments'), ('feature', 'Feature Request'), ('bug', 'Bug Report'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='contact_mes_status_060932_idx'), models.Index(fields=['email'], name='contact_mes_email_a7fb56_idx'), models.Index(fields=['subject'], name='contact_mes_subject_e995b6_idx')],
            },
        ),
    ]
